export const mascota = {
  nombre: '',
  felicidad: 500,
  hambre: 500,
  suenio: 500,
  calor: false,
  limpio: 500,
  diversion: 500,
  dormido: false,
  luz: true,
  luminosidad: null,
  temperatura: null,
  humedad: null,
  fechaNac: Date,
  fechaMuerte: null,
  vivo: true,
};
