export const mascota = {
    nombre: '',
    felicidad: 3000,
    hambre: 3000,
    suenio: 3000,
    calor: false,
    limpio: 3000,
    diversion: 3000,
    dormido: false,
    luz: true,
    temperatura: 30,
    humedad: 80,
    fechaNac: Date,
    fechaMuerte: null,
    vivo: true,
}