export const mascota = {
  nombre: '',
  felicidad: 100,
  hambre: 100,
  suenio: 100,
  calor: false,
  limpio: 100,
  diversion: 100,
  dormido: false,
  luz: true,
  luminosidad: null,
  temperatura: null,
  humedad: null,
  fechaNac: Date,
  fechaMuerte: null,
  vivo: true,
};
